### ISSUE TITLE
Cannot run `python -m omnipose --help`

### ISSUE THREAD

**Issue by lacan** [kevinjohncutler/omnipose#15]
After following your installation instructions on a Win 11 machine
```
conda create -n omnipose pytorch cudatoolkit=11.3 -c pytorch
conda activate omnipose
pip install omnipose
```

I am first met with a missing dependency 
```
ModuleNotFoundError: No module named 'sklearn'
```

After a `pip install sklearn`, running `python -m omnipose --help` results in the following error
```
python.exe: No module named omnipose.__main__; 'omnipose' is a package and cannot be directly executed
```

Running `python -m cellpose --help` works but has no omnipose arguments available

The only way is to build cellpose from source with 
`pip install git+https://github.com/kevinjohncutler/omnipose.git`

**Would it be possible to push the version of omnipose in the repository to pip?**

**Comment by kevinjohncutler** [comment]
@lacan, That's correct, the only way to intall the latest version of Omnipose is with the git command. This is because pip requires all dependecies to be on PyPi (at least, that's my understanding and I have not found a workaround), and I have several dependencies now that are forks of various repos. To get the PyPi package updated, I would need to publish each repo as its own package. This is doable, and I hope to get it done in the next couple weeks. In the meantime, I will remove the pip install omnipose line from the isntlal istructions, as it wasn't clear that doesn't get you the latest version. Thanks for your feedback!

**Comment by kevinjohncutler** [comment]
Got it all sorted out and the latest version of Omnipose (as I write this, v0.3.4) can now be installed via pip!
