### ISSUE TITLE
Install omnipose without GUI dependencies

### ISSUE THREAD

**Issue by ElpadoCan** [kevinjohncutler/omnipose#18]
Hi, I have a suggestion. I know omnipose code is now independent of cellpose 2.0, but I think omnipose installation should still not install the GUI dependencies by default. 

This would be in line with what cellpose does. I say this because `pip install cellpose` works perfectly fine on servers that do not support GUI elements, while `pip install omnipose` will install `PyQt6` which gives me all kinds of errors. 

If you are going to do this, please change also `opencv-python` to `opencv-python-headless` when installing without GUI dependencies in the `cellpose-omni` repo. In general, if you don't need opencv GUI elements, you should be fine installing the headless version. The GUI version often has incompatibilities with other GUI libraries.

**Comment by kevinjohncutler** [comment]
@ElpadoCan this is a great suggestion. I will work on that this week. The reason `opencv-python` is being used `over opencv-python-headless` is an artifact of me solving installation issues on M1/M2 macs, but I'll work out a better solution. Thanks!

**Comment by ElpadoCan** [comment]
Ok great thanks for the quick answer!

One last thing. At the moment we cannot install omnipose in the same environment where we have cellpose 2.0 right? It would be nice if that was  possible.

One way would be to change the name of the `cellpose` folder in your forked cellpose to something like `cellpose_omni` and then change all the imports from `import cellpose` to `import cellpose_omni`. VS code can do that automatically. This way when you install omnipose it will install the `cellpose_omni` package without replacing the existing cellpose 2.0.

I forked your cellpose and did what I just described and it works well now I have both omnipose and Cellpose 2.0 in the same environment. I tested only on Windows but I can test on mac M1 soon. I will let you know thanks!

**Comment by kevinjohncutler** [comment]
@ElpadoCan since setuptools does not allow for default extras, I've decided to keep the GUI in the default installation. Users can now set the environment variable `NO_GUI=True` to disable the GUI. I'm doing this so that I don't have to have a `pip install omnipose[gui] `option. This is mostly an aesthetic choice, but I think this solution will not be a problem for anyone who is advanced enough not to want the GUI at all. Happy to hear pushback on that, of course. 

On the topic of parallel installs with the main `cellpose` branch: you are correct, and I have avoided renaming the package to something other than `cellpose` for compatibility and readability. It is better for me (and I bet others) to be able to use their existing scripts without having to change `cellpose` to `cellpose_omni` everywhere. You are right that VS code makes it easy to make that substitution, but I would prefer to not work with two versions of Cellpose in my head. Some dependencies of the main branch are also outdated and don't play well with those in Omnipose (a relevant example is PyQt6 vs PyQt5), so separating those installs in different conda environments is the best approach if users really need it. The interactive training in CP 2.0 is really cool, but a little ways down my to-do list for Omnipose.

**Comment by ElpadoCan** [comment]
I totally agree on the `NO_GUI` option, however it did not work for me. I set the environment variable to `True` (I figured any string would do the trick) on Windows Powershell and before installing I tested with directly in the terminal the following

**Comment by ElpadoCan** [comment]
Ok never mind, I tried the cloned repo instead of the package from PyPi and it worked, thanks! Just a curiosity, why did you go with a env variable instead of something like `pip install omnipose[no_gui]` ?

Anyway, it works, thanks! 

For the naming of the cellpose package required by omnipose I don't agree :D. The reason is that if you want omnipose to be implemented and installed into other GUIs or pipelines (like I am trying to do within my own GUI) then omnipose cannot delete the current installation of cellpose in that specific GUI (which uses a single environment). Of course, this is just my opinion, so you can choose to do whatever you like with it :D. 

Obviously one cannot install both cellpose GUI and omnipose GUI in the same environment, I agree with that. Still, as far as I can tell, there are no incompatibilities between cellpose and omnipose (both without GUI dependencies) in the same environment. I fear that you might have the same problem with `napari` if you ever plan to make omnipose installable into napari as a plugin, but I am not familiar with napari plugins to say that for certain.

**Comment by kevinjohncutler** [comment]
@ElpadoCan  Glad that worked for you. The reason I could not go with `pip install omnipose[no_gui]` (despite many hours of researching how to get that to work) is because setuptools does not allow you to exclude dependencies based on pip arguments or use default extras. Both of these options would work and several threads exist with people advocating for their implementation, but it's not supported as of now (and those threads seem to indicate they never will be). 

As to concurrent installs of cellpose and omnipose, I should do some more testing. It used to be that the only way to install the most recent version of omnipose was via github, not pip, and therefore installation of omnipose would overwrite any existing installs of cellpose with my own fork. But pip will happily install cellpose alongside cellpose-omni and I am not sure how python decides with package to use for `import cellpose`. 

You are quite right about plugins. I need to work more on a celllprofiler plugin, and napari after that. In both cases, I expect that the cellpose plugin will be in conflict with the omnipose plugin due to cellpose-omni. The obvious solution is the one you propose, renaming the cellpose-omni package to something besides cellpose, but I am still not convinced that there is any good reason to have cellpose installed alongside cellpose-omni. I will make `pip uninstall cellpose` part of the omnipose installation instructions. (Another limitation of setuptools... no way to specify an uninstall, right?)

**Comment by ElpadoCan** [comment]
Oh yeah, you are right, I never thought about excluding dependencies from the default, it sounds like it would be a valuable feature to have then :D. 

Well, then one way to do it is not to install the GUI dependencies by default and then when the user asks to open the GUI then in the script runs `subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'PyQt5])` for each one of the missing GUI libraries. I do that all the time in my own GUI and it works pretty well (I think it is also the way plugins are installed in napari). 

Anyway, the reason to have cellpose and omnipose in the same env is because why not? For example, I have my own GUI where the user can choose which model he/she wants to use, and so far the only one not compatible is omnipose :D. 

I have cellpose, yeaz, yeastmate and stardist and they are all compatible with each other. Having cellpose uninstalled when you install omnipose is pretty annoying. At the moment I solved with forking your cellpose-omni and changing the cellpose package name imported and so far is working fine. 

Thanks for answering all the questions and happy developing!
