### ISSUE TITLE
Segmentation of C elegans

### ISSUE THREAD

**Issue by LRpz** [kevinjohncutler/omnipose#2]
Hi, 

I was wondering whether the 'bact_omni' model could be used to segment C elegans grayscale images as shown in Figure 5. 
I only get oversegmented patches in some worms regardless of the diameter setting value.

Diameter=20
![C_elegans_d=20](https://user-images.githubusercontent.com/29403104/153459726-7052c63d-2254-4436-ab5c-6e15209426f0.PNG)

Diameter=250
![C_elegans_d=250](https://user-images.githubusercontent.com/29403104/153459811-8b164013-9bfe-4677-8117-09285e4699d4.PNG)

Would you suggest changing model/training my own?
Thanks a lot

**Comment by kevinjohncutler** [comment]
Hi @LRpz, sorry for the late reply. I have a model trained for c_elegans that I don't think is built in yet through cellpose. I'd be happy to send it to you (it is too big to host on github); send me an email at kcutler@uw.edu. Please share a raw example image too so that I can recommend the best settings as well.
