### ISSUE TITLE
Training cellpose-omni using the API

### ISSUE THREAD

**Issue by Jolanda5** [kevinjohncutler/omnipose#56]
I am trying to replace the use of cellpose by using cellpose-omni in our code. I try to run the training on a fedora machine and I use the most current version of code from this github.
I think there is a problem with the `links` parameter. As far as I have understood the documentation, you are not required to specify `links`, so I don't pass any.
I define the model like this:
```
from cellpose_omni import models
model = models.CellposeModel(
        pretrained_model=pretrained_model_path,
        gpu=True,
        device=device,
        model_type=config.get("cp_model_type", None),
        net_avg=config.get("net_avg", False),
        diam_mean=config.get("diam_mean", 30.0),
        nchan=config.get("nchan", 2),
        dim=2 if is_2d else 3,
    )
```
and the train like this:
```
model.train(
        train_data=train_imgs,
        train_labels=train_labels,
        train_files=None,
        test_data=valid_imgs,
        test_labels=valid_labels,
        test_files=None,
        channels=channels,
        normalize=normalize,
        save_path=save_path,
        save_every=save_every,
        save_each=save_each,
        learning_rate=learning_rate,
        n_epochs=n_epochs,
        momentum=momentum,
        SGD=SGD,
        weight_decay=weight_decay,
        batch_size=batch_size,
        nimg_per_epoch=None,
        rescale=rescale,
        min_train_masks=min_train_masks,
    )
```

I got a series of errors and did a series of fixes:
```
Traceback (most recent call last):
  File "cellpose_omni_cnn_config.py", line 213, in <module>
    train()
  File "cellpose_omni_cnn_config.py", line 188, in train
    model.train(
  File "lib/python3.10/site-packages/cellpose_omni/models.py", line 1177, in train
    train_labels = labels_to_flows(train_labels, train_links, files=train_files, 
TypeError: labels_to_flows() got multiple values for argument 'files'
```
This was easily fixable by changing it to this:
```
train_labels = labels_to_flows(labels=train_labels, 
                                           links=train_links, files=train_files, 
                                           use_gpu=self.gpu, device=self.device, dim=self.dim)
```
The next error was this:
```
Traceback (most recent call last):
  File "cellpose_omni_cnn_config.py", line 213, in <module>
    train()
  File "cellpose_omni_cnn_config.py", line 188, in train
    model.train(
  File "lib/python3.10/site-packages/cellpose_omni/model
s.py", line 1198, in train
    model_path = self._train_net(train_data, train_labels, train_links,
  File "lib/python3.10/site-packages/cellpose_omni/core.py", line 1134, in _train_net
    imgi, lbl, scale = transforms.random_rotate_and_resize([train_data[i] for i in inds],
  File "lib/python3.10/site-packages/cellpose_omni/transforms.py", line 908, in random_rotate_and_resize
    scale_range=scale_range, xy=xy,
UnboundLocalError: local variable 'xy' referenced before assignment
```
which I fixed by adding
```
         if tyx is None:
             xy = (224,)*dim
+        else:
+            xy = tyx
```
which I hope is correct? The docstring of `random_rotate_and_resize` seems to be inconsistent about xy/tyx also.

The next error then is:
```
Traceback (most recent call last):
  File "cellpose_omni_cnn_config.py", line 213, in <module>
    train()
  File "cellpose_omni_cnn_config.py", line 188, in train
    model.train(
  File "lib/python3.10/site-packages/cellpose_omni/models.py", line 1199, in train
    model_path = self._train_net(train_data, train_labels, train_links, 
  File "lib/python3.10/site-packages/cellpose_omni/core.py", line 1150, in _train_net
    links = [train_links[idx] for idx in inds]
  File "lib/python3.10/site-packages/cellpose_omni/core.py", line 1150, in <listcomp>
    links = [train_links[idx] for idx in inds]
TypeError: 'NoneType' object is not subscriptable
```
I replaced that line with:
```
if train_links:
   links = [train_links[idx] for idx in inds]
else:
   links = []
```
Is this fix reasonable?

Afterwards I get this index error:
```
Traceback (most recent call last):
  File "cellpose_omni_cnn_config.py", line 213, in <module>
    train()
  File "cellpose_omni_cnn_config.py", line 188, in train
    model.train(
  File "lib/python3.10/site-packages/cellpose_omni/models.py"
, line 1199, in train
    model_path = self._train_net(train_data, train_labels, train_links,
  File "lib/python3.10/site-packages/cellpose_omni/core.py", 
line 1155, in _train_net
    out = omnipose.core.masks_to_flows_batch(lbl, links,
  File "lib/python3.10/site-packages/omnipose/core.py", line 421, in masks_to_flows_batch
    ccoords = np.unravel_index(indices,final_shape)
  File "<__array_function__ internals>", line 180, in unravel_index
ValueError: index 94405010865648 is out of bounds for array with size 752640
```
which I fixed by adding
```
+    if len(links) == 0:
+        links = len(masks) * [None]
     for i,(masks,lnks) in enumerate(zip(masks,links)):
         mask_temp = np.ravel(masks)
```
Is this fix reasonable?

The next issue is the following:
```
lib/python3.10/site-packages/omnipose/core.py:719: VisibleDeprecationWarning: Creating an ndarray from ragged
 nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is 
deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  affinity_graph = np.logical_or.reduce(conditions)
Traceback (most recent call last):
  File "cellpose_omni_cnn_config.py", line 213, in <module>
    train()
  File "cellpose_omni_cnn_config.py", line 188, in train
    model.train(
  File "lib/python3.10/site-packages/cellpose_omni/model
s.py", line 1199, in train
    model_path = self._train_net(train_data, train_labels, train_links,
  File "lib/python3.10/site-packages/cellpose_omni/core.py", line 1155, in _train_net
    out = omnipose.core.masks_to_flows_batch(lbl, links, 
  File "lib/python3.10/site-packages/omnipose/core.py", line 432, in masks_to_flows_batch
    affinity_graph = masks_to_affinity(clabels, ccoords, steps, inds, idx, fact, sign, dim, 
  File "lib/python3.10/site-packages/omnipose/core.py", line 719, in masks_to_affinity
    affinity_graph = np.logical_or.reduce(conditions)
ValueError: could not broadcast input array from shape (9,52016,224) into shape (9,52016)
```
And this is where my fixes end because I don't know what would be a fix for this and if my fixes in between have been wrong already and thus produced this error in sizes. Can you please help me with that?

**Comment by kevinjohncutler** [comment]
@Jolanda5 sorry I didn't see this until now. I always train via CLI, and so __main__.py first calls io.load_train_test_data(). In that function, link file names are created and loaded via load_links, which returns an empty list if the link file is found for a corresponding image and label matrix. So even through the default for links is None in the function arguments, it needs to be a list of lists when used on its own. This is what is causing the downstream issues when training using model.eval() directly. 

That first error is somewhat surprising, but I will make that change anyway since specifying parameter names does no harm. The second error is indeed a bug, and your fix works. However, being in that branch means that you do not have omni=True. Is this what you intended? xy is a vestige of cellpose, which only does 2D segmentation (and also mixed up x and y), so for 3D I use tyx (proper ordering, and also not zyx simply because I mostly do 2D+T and not spatial 3D).

**Comment by Jolanda5** [comment]
Thank you for your answer. I checked `load_train_test_data()` and saw that there is this:
```
if not do_links:
        links = [None]*nimg_train
        test_links = [None]*nimg_test
```
I implemented this in `train()` like this (right after the `transforms.reshape_train_test()` call):
```
if train_links == None:
            train_links = [None] * len(train_data)
if run_test:
            test_links = [None] * len(test_data)
```
and still get the same error `ValueError: could not broadcast input array from shape (9,52016,224) into shape (9,52016)`.
As you said, `load_links()` produces a list of empty lists instead. So I also tried it like this:
```
if train_links == None:
            train_links = [[] for _ in range(len(train_data))]
if run_test:
            test_links = [[] for _ in range(len(test_data))]
```
and still get the same error `ValueError: could not broadcast input array from shape (9,52016,224) into shape (9,52016)`.

Yes, we intended to not use omni=True right now. We wanted to try both omnipose and cellpose_omni and compare them to see which works better for our purposes. Because as far as we understood, cellpose_omni already has benefits compared to cellpose.

**Comment by Jolanda5** [comment]
I just realised that with commit e9116018617a81231f99624dccc2adff55689ae0 you changed the default for CellposeModel from omni=False to omni=True which means the last test runs I made were done with omni=True, which therefore also doesn't work.

**Comment by kevinjohncutler** [comment]
Quick followup: this minimal example works to train via a notebook. 
```python
model_name = 'bact_phase_omni'
model = models.CellposeModel(gpu=use_GPU, model_type=model_name)
chans = [0,0]
model.train(
        train_data=[imgs[i] for i in n],
        train_labels=masks,
        train_links = [None for i in n],
        channels=chans,
    )
```
Here, masks is a list of masks that came from evaluating the model on that image list (just convenient to plop this in the mono_channel_bact example). The channels parameter is super important, since that informs how `load_train_test_data` transforms the images. It is a historical quirk of Cellpose that my earlier models, and all of Cellpose's, are 2-channel models (even when trained on single-channel data, they are padded with a second channel of `0`s). If you need to start form a pre-trained model, be sure that the channels parameter matches the model.

**Comment by Jolanda5** [comment]
But this short example uses omnipose (omni=True) and not omni=False, right?

**Comment by Jolanda5** [comment]
Concerning the channels parameter, when specifying `channels=[0,0]`, my data gets transformed from shape `(3, 300, 300)` to `(6, 1, 300)` (I was wondering why it always printed `INFO: >>>> training network with 6 channel input <<<<` no matter if I specified `nchan=2` or `nchan=3`). I am currently trying to figure out this difference in behaviour from cellpose to omnipose. (When specifying `channels=None` in `train()` it leaves my data with the correct shape `(3, 300, 300)`).

**Comment by kevinjohncutler** [comment]
Oh, yes, I did forget to set `model.omni=False`. Upon doing so, I get the `ValueError: could not broadcast input array from shape`. I will dig into that. 

Regarding channels, something to be aware of is that you will need to train a new model from scratch if you want all three of your channels to contribute toward segmentation (via CLI, `--all_channels `does this, which avoids messing up the data). That said, the expected behavior is that the input images are formatted to 2-channel if you have a `channels` tuple. 

Regarding the reshape code:

```python
data = data.astype(np.float32)
    if data.ndim < 3: # plain 2D images get a new channel axis 
        data = data[...,np.newaxis]
    elif data.shape[0]<8 and data.ndim==3: # Assume stack of this sort are nchan x Ly x Lx, so reorder to Ly x Lx x nchan 
        data = np.transpose(data, (1,2,0))
    # use grayscale image
    if data.shape[-1]==1:
        data = np.concatenate((data, np.zeros_like(data)), axis=-1)
    else:
        if channels[0]==0:
            # data = data.mean(axis=-1, keepdims=True) # why do this? Seems like it would be smashing channels together instead of taking the 0th one. 
            data = data.mean(axis=channel_axis, keepdims=True) # also had a big bug: 3D volumes get squashed to 2D along x axis!!! Assumptions bad. 
            
            data = np.concatenate((data, np.zeros_like(data)), axis=-1) # forces images to always have 2 channels, possibly bad for multidimensional
        else:
            chanid = [channels[0]-1] # oh so [0,0] would do a mean and [1,0] would actually take the first channel?
            if channels[1] > 0:
                chanid.append(channels[1]-1)
            data = data[...,chanid]
            for i in range(data.shape[-1]):
                if np.ptp(data[...,i]) == 0.0:
                    if i==0:
                        warnings.warn("chan to seg' has value range of ZERO")
                    else:
                        warnings.warn("'chan2 (opt)' has value range of ZERO, can instead set chan2 to 0")
            if data.shape[-1]==1:
                data = np.concatenate((data, np.zeros_like(data)), axis=-1)
    if chan_first:
        if data.ndim==4:
            data = np.transpose(data, (3,0,1,2))
        else:
            data = np.transpose(data, (2,0,1))
    return data
```
You are right to call attention to the previous transpose call. Adding `channel_axis = -1` to that branch should fix it. The channel_axis parameter is really important for 3D multichannel data.

**Comment by kevinjohncutler** [comment]
So, the error ultimately comes from my recent (and substantial) speedups to the training loop. I made a new function `masks_to_flows_batch`, which expects the `lbl` batch to be just instance labels, not the full set of network predictions. This is because the distance field and its gradient depend sensitively on morphology, which is changed during image augmentations with an affine transformation. Cellpose's augmentations just do scaling and rotation, not shear/anisotropic scaling, so morphology was unchanged and they were able to simply transform precomputed flow field. In Omnipose, the distance field has to be recomputed from the transformed label matrices. 

I determined that the best course of action was to simply avoid the Cellpose training augmentations and loss functions. This is probably best from the point of view of comparing the two methods anyway, as it limits the variable to the network outputs. That is, `omni=False` will only revert back to cell probability and flow during training (and choose the cellpose mask reconstruction during evaluation). 

My parallelized code caused some bugs with centroid computation, but I think I fixed those. Before pushing a new version, I need to clean up a lot of the debugging code. 

@Jolanda5, are your cells all quite round? I'm skeptical that the center-seeking cellpose field will be better (it never has been on any datasets we have tested), but I also have never tested it on high-quality, purely-round ground truth images. The lack of detail in the Cellpose flow could lead to more robust (albeit fuzzier) predictions at boundaries and thus lead to less under-segmentation. _I.e._, Cellpose flows are better suited to less accurately-annotated ground truth data.

**Comment by Jolanda5** [comment]
Thanks for looking into it :)

Our cells actually have a variety of shapes and we also saw the problems with false splits in elongated cells when we used cellpose. We also expect omnipose to perform better than cellpose on our data but we wanted to try both anyways.

**Comment by kevinjohncutler** [comment]
No problem. I just pushed those changes; let me know how it goes, especially with the channels.

**Comment by Jolanda5** [comment]
The channels parameter now works as I expected again.
Training with omni=False also works now, thanks for your fixes :)

Just a quick last hint: In 4637cc2a99fef6fbdbba0303d55a86eab366ef4e, you renamed `omnipose.dataset` to `omnipose.data.train_set`, which doesn't exist in the data.py file (`AttributeError: module 'omnipose.data' has no attribute 'train_set'`).
