### ISSUE TITLE
Examples mono_channel_bact jupyter kernel crashes

### ISSUE THREAD

**Issue by tensorcoder** [kevinjohncutler/omnipose#66]
Hi I used this package a few months ago and it was all working fine. 

Now on a fresh install and new environment I cannot run the Jupyter Notebook second cell in examples/mono_channel_bact.ipynb

When "from cellpose_omni import models, core" is included, the kernel crashes without any error message.

**Comment by Marco-J-K** [comment]
Sounds similar to the issue I had and reported recently. For me, the problem was coming from numpy and natsort packages not being installed properly when following the install procedure in the readme. I uninstalled numpy and reinstalled the same version, then installed natsort and it worked. Check out this issue as well: https://github.com/kevinjohncutler/omnipose/issues/63

**Comment by kevinjohncutler** [comment]
Let's continue this on #63.
