### ISSUE TITLE
Issue with Continuing Training on bact_phase_omni Model

### ISSUE THREAD

**Issue by 73Emilie** [kevinjohncutler/omnipose#69]
I'm trying to continue training on the bact_phase_omni model. Here's the command I used:

omnipose --train --use_gpu --dir /Users/emiliefeng/Downloads/training \
--mask_filter _masks \
--nchan 2 --nclasses 3 \
--learning_rate 0.1 --RAdam --batch_size 16 --n_epochs 4000 \
--pretrained_model bact_phase_omni

However, after training, when I test this new model, I encounter the following error:

ERROR: Error(s) in loading state_dict for CPnet:
    size mismatch for downsample.down.res_down_0.conv.conv_0.0.weight: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([1]).
    size mismatch for downsample.down.res_down_0.conv.conv_0.0.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([1]).
    size mismatch for downsample.down.res_down_0.conv.conv_0.0.running_mean: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([1]).
    size mismatch for downsample.down.res_down_0.conv.conv_0.0.running_var: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([1]).
    size mismatch for downsample.down.res_down_0.conv.conv_0.2.weight: copying a param with shape torch.Size([32, 2, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 1, 3, 3]).
    size mismatch for downsample.down.res_down_0.proj.0.weight: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([1]).
    size mismatch for downsample.down.res_down_0.proj.0.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([1]).
    size mismatch for downsample.down.res_down_0.proj.0.running_mean: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([1]).
    size mismatch for downsample.down.res_down_0.proj.0.running_var: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([1]).
    size mismatch for downsample.down.res_down_0.proj.1.weight: copying a param with shape torch.Size([32, 2, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 1, 1, 1]).

I suspect the issue might be related to nchan, as I used grayscale images for training and testing. Could anyone help me understand and resolve this error?

Thank you!

**Comment by vhickl** [comment]
Hi, any more luck fixing this? I'm running into the similar error message even though I'm ostensibly doing something more straightforward: I'm just retraining the bact_phase_omni model from scratch using the instructions in https://omnipose.readthedocs.io/training.html.

My exact training command is `omnipose --train --use_gpu --dir T:\users\hivi\Omnipose_training_data\bact_phase\train_sorted --mask_filter _masks --n_epochs 4000 --pretrained_model None --learning_rate 0.1 --diameter 0 --batch_size 16 --RAdam --nclasses 3 --look_one_level_down --save_every 10 --save_each --verbose`

I did have to tweak the code slightly (see my issue #68) but I don't know if that's the problem since you're getting the same error after training.

Out of curiosity, do you test the model in the GUI? I get a PermissionError when trying to add my model using "Models>Add custom torch model to GUI", and it's when I then try to use the model anyways that I get your error. I can't find any documentation at the moment on how to use my own trained model in a notebook.

**Comment by vhickl** [comment]
Hi again. So for me it turns out out I was just incorrectly setting nchan=2 during training when my model had nchan=1. Since the docs say that bact_phase_omni has nchan=2 I somehow assumed my retrained version would be the same, but that is not the case. When I set nchan=1 during segmentation everything seems to work fine. 

Have you tried training and segmenting with nchan 1 and nclasses 3? That's the only obvious difference I see between our cases.

**Comment by kevinjohncutler** [comment]
@73Emilie @vhickl Sorry for the delay. I decided to make nchan=1 by default, as that fits most people's use case. Retraining from an existing model requires you to keep the original number of channels for that given model, but training a new model from scratch will default to 1. Similar for nclasses; all published Omnipose models have 3, but I have since determined that the boundary output is no longer necessary, so the default is 2. This is the original source of error that @73Emilie came up against, as it should have been --nchan 2 --nclasses 3.
