### ISSUE TITLE
Flows to mask

### ISSUE THREAD

**Issue by phisanti** [kevinjohncutler/omnipose#91]
Hi, I like the approach of using flow masks for bacterial cell segmentation. It works really well in highly dense areas. However, I am not getting the expected output. When I pass a labelled image (0 for background and int-n for each cell), I get a 4 dimension image: source, pmap, flow1, flow2. If I understand your documentation, the flow map should encode background as -5, but in my case, it comes as 0. Also, I am not able to reconvert the flow maps into pmaps. Ideally, I would like to train my model to output two channels (pmaps) and then convert to pmap. 

Please let me know if you can help; any advice will be highly appreciated.

This is how I get the flow maps:

```
test=labels_to_flows(batch_img_tensor, use_gpu=False, device=None, redo_flows=True)
```
And this is how I get the mask back from the flows (channels 2 and 3 from the previous image)

```
flows=test[2:]
z2=get_masks(flows)
```

**Comment by kevinjohncutler** [comment]
@phisanti Good question; the -5 for background is added in the training loop after generating the distance field rather than than being hardcoded into the distance field calculation. You can set the mask_threshold to something >0 or manually set the 0 values to -5 to get the mask reconstruction to work properly on generated fields, which is what I have done for debugging in the past. 

Also note that the first argument to `utils.get_masks()` is `p`:
```
    p: float32, ND array
        final locations of each pixel after dynamics 
```
But your are passing in the flow and distance field as a list:
```
    flows: list of [4 x Ly x Lx] arrays
        flows[k][0] is labels[k], flows[k][1] is cell distance transform, flows[k][2:2+dim] are the 
        (T)YX flow components, and flows[k][-1] is heat distribution / smooth distance 
```

You would need to run Euler integration first to get `p`. What is your intended use case? What do you mean by pmap?

**Comment by kevinjohncutler** [comment]
@phisanti closing for now, please reopen if you need further help or feel free to email me.
